services:
  hbase-gateway:
    environment:
      SECRET_PROVIDER: ansible-vault
      ANSIBLE_VAULT_FILE: /run/config/hbase.vault.yml
      ANSIBLE_VAULT_PASSWORD_FILE: /run/secrets/ansible_vault_password
      HBASE_GATEWAY_USERNAME: ""
      HBASE_GATEWAY_PASSWORD: ""
    volumes:
      - ./secrets/hbase.vault.yml:/run/config/hbase.vault.yml:ro
    secrets:
      - ansible_vault_password

  api:
    environment:
      SECRET_PROVIDER: ansible-vault
      ANSIBLE_VAULT_FILE: /run/config/hbase.vault.yml
      ANSIBLE_VAULT_PASSWORD_FILE: /run/secrets/ansible_vault_password
      HBASE_GATEWAY_USERNAME: ""
      HBASE_GATEWAY_PASSWORD: ""
    volumes:
      - ./secrets/hbase.vault.yml:/run/config/hbase.vault.yml:ro
    secrets:
      - ansible_vault_password

secrets:
  ansible_vault_password:
    environment: ANSIBLE_VAULT_PASSWORD